DROP TABLE IF EXISTS custom;
DROP TABLE IF EXISTS sample;
DROP TABLE IF EXISTS updatedsm;

CREATE TABLE custom (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dsm_name TEXT NOT NULL,
  ec_regex TEXT NOT NULL,
  eid_regex TEXT NOT NULL,
  payload TEXT NOT NULL,
  last_edit TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sample (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dsm_name TEXT NOT NULL,
  payload TEXT NOT NULL,
  ec TEXT NOT NULL,
  eid TEXT NOT NULL,
  lstime TEXT NOT NULL,
  last_view TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE updatedsm (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dsm_name TEXT NOT NULL,
  current_ver TEXT NOT NULL,
  latest_ver TEXT NOT NULL
);